### ISSUE TITLE
cmdheight=0 makes the last line disappear behind the statusline at the bottom

### ISSUE THREAD

**Issue by angelus2014** [Allaman/nvim#22] opened 2022-10-06 18:37 UTC
Hello,

I noticed that the last line of the text was hidden behind the statusline at the bottom. Turns out that the default setting in your configuration for cmdheight was the problem. After setting it to 1, the issue is gone.

---
With regards,

Angelo Machils

**Comment by Allaman** [comment] 2022-10-06 18:56
Hi, 

That`s strange because I experienced the same issue but just with a new plugin (see https://github.com/Allaman/nvim/commit/4fb5ad37f45f645c8b4c6175b0647c86d382b90f) and not related to cmdheight which is still 0 for me

At the moment I have no clue if there is a relation or what the root cause for this behaviour is :(


You have this issue without said plugin? 

Best regards
Michael

**Comment by angelus2014** [comment] 2022-10-06 19:07
I commented out that whole section for the 'noice' plugin and reverted the cmdheight setting and yes, that also solves the issue. But it could also be one of the required plugins in that section that could be the culprit. I will test some more with keeping the said plugin, but disabling the required ones one-by-one to see if that makes a difference. But that will be some time tomorrow. Will report back then.


---
With regards,

Angelo Machils

**Comment by angelus2014** [comment] 2022-10-07 08:06
Hello,

Disabling/Enabling the required plugins doesn't make a difference. What seems to happen is that when the 'noice' plugin 'kicks in' (after the first move of the cursor), the  whole text moves down one line, putting the last line under the statusline. It could also be an issue that only affects when using the 'mini.nvim' statusline. If/When I have some time, I will see if it's also an issue with a different statusline.


---
With regards,

Angelo Machils

**Comment by Allaman** [comment] 2022-10-07 08:21
Hi, 
thanks for your researches. When I uncomment mini statusline the issue still exists. When I use a minimal lualine setup instead, the issue also occurs.
Can you please confirm this by putting this in your plugins.lua
```
  use({
    "nvim-lualine/lualine.nvim",
    requires = {
      "kyazdani42/nvim-web-devicons",
    },
      config = function()
        require("lualine").setup()
      end,
  })
```
And commenting out the mini part  https://github.com/Allaman/nvim/blob/main/lua/config/mini.lua#L74-L114

**Comment by angelus2014** [comment] 2022-10-07 09:06
Hello,

On 7 Oct 2022, at 11:21, Michael Peter wrote:

> thanks for your researches. When I uncomment mini statusline the issue still exists. When I use a minimal lualine setup instead the issue (even more worse) also occurs.
>
> Can you please confirm this by putting this in your plugins.lua

Yes, with Lualine it happens as well. One difference, when moving the cursor to that particular line, the status line disappears and one can see/edit that line of text.
Not sure if this is related, but I also noticed that some notifications appear 2 or even 3 times in the top right corner. I don’t know if these are all ‘noice’ notifications though.

---
With regards,

Angelo Machils

**Comment by Allaman** [comment] 2022-10-07 09:11
> Not sure if this is related, but I also noticed that some notifications appear 2 or even 3 times in the top right corner. I don’t know if these are all ‘noice’ notifications though.

Same for me. For instance when searching with no result or when closing with unsaved buffer. 

I think that I will wait a little because of the nature of noice being a "Highly experimental plugin [...]" and there is much development going on

**Comment by Allaman** [comment] 2022-10-19 21:44
Hi @angelus2014, is the issue fixed for you? For me it is still the same :(

**Comment by angelus2014** [comment] 2022-10-21 08:19
Hello @Allaman,

Yes, it's still the same for me as well.


---
With regards,

Angelo Machils

**Comment by Allaman** [comment] 2022-10-21 12:47
@angelus2014 see the commit... very odd

**Comment by angelus2014** [comment] 2022-10-21 13:03
@Allaman; I will have a look a little later today.

**Comment by Allaman** [comment] 2022-10-22 09:29
Issue still occasionally occurs :/

**Comment by angelus2014** [comment] 2022-10-22 14:32
Hmmm, I can only reproduce the issue when inside tmux. But tbh, I only had a little time to test.

Addendum: interesting, in Alacritty it still happens, even while not using tmux. In Wezterm however, only when using tmux...... Granted, I have setup Alacritty to disable all window decorations, so that could be an influence.

Addendum 2: yes, it was the `window decoration` setting in Alacritty. So as far as I can tell, it seems to be limited to tmux.

---
With regards,

Angelo Machils

**Comment by Allaman** [comment] 2022-10-22 16:33
Hmm, nice find. I will try to confirm this. I am also a heavy tmux user so that would make sense (with kitty)

**Comment by angelus2014** [comment] 2022-10-22 17:01
Okay, in the default macOS Terminal.app it doesn't occur at all, not even while inside tmux........ :) I will see if tomorrow I can test it inside iTerm2 but it seems to be dependent on a variety of factors.

Addendum: well, no time like now :) iTerm2 (the latest nightly version from Homebrew) shows the same pattern as Terminal.app, no issues, whether or not one uses tmux............ Interesting :)

**Comment by Allaman** [comment] 2022-10-22 20:47
I was working the last couple of hours without tmux (in kitty) and the issue didn't occur. But I don't really know how to trigger this behaviour so we should consider this with caution :D 

This drives me nuts

**Comment by Allaman** [comment] 2023-01-02 21:06
Meanwhile, the issue hasn't occurred again (for me), so I am closing this for now

**Closed as completed by Allaman** 2023-01-02 21:06 UTC
